class Comment(Enum):
     BALL_MAYBE_OUT = 0
     BALL_OUT = 1
     CELEBRATION = 3
     GOAL = 4
     REPLAY = 6
     FREE_KICK = 7
     GOAL_KICK = 8
     PITCH_INVADED = 10
     NON_OFFENSIVE_ASSAULT = 11
     OFFENSIVE_ASSAULT = 13